version: '3'

services:
  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    deploy:
      placement:
        constraints:
          - node.role == worker
      # resources:
      #   limits:
      #     cpus: "0.50"
      #     memory: 50M
      #   reservations:
      #     cpus: "0.25"
      #     memory: 20M
    networks:
      - monitor-net
  
  cadvisor:
    image: google/cadvisor:latest
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    deploy:
      mode: global
      # resources:
      #   limits:
      #     cpus: "0.50"
      #     memory: 50M
      #   reservations:
      #     cpus: "0.25"
      #     memory: 20M
    ports:
      - "8080:8080"
    networks:
      - monitor-net
      
  grafana:
    image: softway/grafana:2.0
    # image: grafana/grafana:latest
    # build: .
    #volumes: 
    #  - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=VD1@dm1n
      - GF_USERS_ALLOW_SIGN_UP=false
    #depends_on:
    #  - prometheus
    networks:
      - monitor-net
    ports:
      - "3000:3000"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "1.0"
          memory: 50M
      placement:
        constraints: [node.role == worker]
  
volumes:
  grafana_data:
    external: true

networks:
  monitor-net:
    driver: overlay