FROM grafana/grafana:latest
MAINTAINER Tanawat Thongsang tanawat.th@inet.co.th

RUN grafana-cli plugins install jasonlashua-prtg-datasource
RUN grafana-cli plugins install alexanderzobnin-zabbix-app
RUN grafana-cli plugins install grafana-worldmap-panel
RUN grafana-cli plugins install satellogic-3d-globe-panel
RUN grafana-cli plugins install jdbranham-diagram-panel
RUN grafana-cli plugins install agenty-flowcharting-panel
RUN grafana-cli plugins install savantly-heatmap-panel
RUN grafana-cli plugins install simpod-json-datasource
RUN grafana-cli plugins install grafana-kubernetes-app
RUN grafana-cli plugins install michaeldmoore-multistat-panel
RUN grafana-cli plugins install vonage-status-panel
RUN grafana-cli plugins install grafana-simple-json-datasource
RUN grafana-cli plugins install corpglory-progresslist-panel